[package]
name = "deadlock-mod-manager"
version = "0.5.1"
description = "A mod manager for the Valve game Deadlock, built with Tauri, React, and TypeScript."
authors = ["stormix <contact@stormix.co>"]
license = "GPL-3.0"
repository = "https://github.com/stormix/deadlock-modmanager"
homepage = "https://github.com/stormix/deadlock-modmanager"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-os = "2.2.0"
tauri-plugin-upload = "2"
tauri-plugin-store = "2.2.0"
tauri-plugin-fs = "2.2.0"
vdf-parser = "0.1.8"
keyvalues-serde = "0.2"
regex = "1.11.1"
zip = "2.2.2"
tempfile = "3.14.0"
unrar = "0.5.7"
thiserror = "2.0.9"
sysinfo = { version = "0.33.0", features = ["windows"] }
tauri-plugin-log = "2"
log = "0.4"
tauri-plugin-process = "2.2.0"
sevenz-rust = "0.5"
tauri-plugin-sentry = "0.3"
steamlocate = "2.0.0"

# Optimized for bundle size. If you want faster builds comment out/delete this section.
[profile.release]
lto = true        # Enable Link Time Optimization
opt-level = "z"   # Optimize for size.
codegen-units = 1 # Reduce number of codegen units to increase optimizations.
panic = "abort"   # Abort on panic
strip = true      # Automatically strip symbols from the binary.
debug = false

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-single-instance = "2.2.2"
tauri-plugin-updater = "2.3.0"
