name: Update AUR PKGBUILD for new release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to publish to AUR (e.g., v0.5.0)"
        required: true
        type: string

jobs:
  aur-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone from AUR
        run: git clone https://aur.archlinux.org/deadlock-modmanager.git

      - name: Update pkgver
        run: |
          cd deadlock-modmanager
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION=${{ github.event.inputs.release_tag }}
            VERSION=${VERSION#v}
          else
            VERSION=${GITHUB_REF##*/v}
          fi
          sed -i "s/^_pkgver=.*/_pkgver=${VERSION}/" PKGBUILD
          sed -i -E "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@2ac5a4c1d7035885d46b10e3193393be8460b6f1
        with:
          pkgname: deadlock-modmanager
          pkgbuild: deadlock-modmanager/PKGBUILD
          commit_username: GitHub Actions
          commit_email: github-actions@github.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag || github.ref_name }}
          updpkgsums: true
